coverage:
  range: 50..100

github_checks:
    annotations: false    # turn back on when our coverage is more decent - they are just annoying for now

ignore:
    - "*/contrib/*"
    - "*/Protocols/*"
    - "*/setup.py"
    - "*/setup_exe.py"
    - "*/Hardware/*"


#    - "*/DSView/*" # (GUI code) - TODO find a way to add display options back in
#    - "*/LMVis/Extras/*"
#    - "*/ui/*"
#    - "*/loft/*"
#    - "*/Loft/*"

flags:
  all:
    paths:
      - "*"
      
   core:
     ignore:
       - "*/ui/*"
       - "*/Acquire/*"
       - "*/DSView/*"
       - "*/LMVis/*"
       - "*/recipes/recipeGui.py"
       - "*/recipes/vertical_recipe_display.py"
       - "*/ParallelTasks/*"
       - "*/tileviewer/*"
       - "*/contrib/*"
      
