  version: 1
  disable_existing_loggers: false
  formatters:
      simple:
          format: "%(levelname)s:%(name)s:%(message)s\n"

      time:
          format: "%(asctime)s : %(levelname)s : %(name)s : %(message)s\n"

  handlers:
      console:
          class: logging.StreamHandler
          level: INFO
          formatter: simple
          stream: ext://sys.stdout

      file:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: simple
          filename: PYMEAcquire.log #Alter to make sure directory is OK - this will dump log in current directory
          maxBytes: 1000000
          backupCount: 3


  root:
      level: DEBUG
      handlers: [console, file ]
